#!/usr/bin/env python3
// List all databases in MongoDB
import pymongo

def list_databases():
    """
    List all databases
    """
    client = pymongo.MongoClient()
    databases = client.list_database_names()
    for db in databases:
        print(db)

if __name__ == "__main__":
    list_databases()
