#!/usr/bin/env python3

from pymongo import MongoClient

def list_databases():
    """
    List all databases in MongoDB.
    """
    client = MongoClient()
    databases = client.list_database_names()
    for db in databases:
        print(db)

if __name__ == "__main__":
    list_databases()
